---
# Define the hooks to be executed before each commit.
# Documentation: https://pre-commit.com/index.html
default_stages: [commit]
repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npm run eslint:fix
        language: system
        types: [file, javascript]
        pass_filenames: false
  - repo: local
    hooks:
      - id: prettier
        name: prettier XML
        entry: npm run prettier:xml
        language: system
        types: [file, xml]
        exclude_types: [svg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types: [svg]
      - id: trailing-whitespace
  - repo: https://github.com/crate-ci/typos
    rev: v1.15.2
    hooks:
      - id: typos
        args: [--format, brief, --write-changes]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.23.2
    hooks:
      - id: check-dependabot
        name: validate dependabot
      - id: check-github-workflows
        name: validate github workflows
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.11.0
    hooks:
      - id: yamlfix
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.4.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
