name: "🤩 Feature Request"
description: Request a feature for boonGUI which you would like to see in a future release.
title: "[Feature]: "
labels: "Nice to have"
body:
  - type: checkboxes
    attributes:
      label: Before You Submit Your Feature Request
      options:
        - label: I have searched the [issue tracker](https://github.com/LangLangBart/boonGUI/issues) for a feature request that matches the one I want to file, without success.
          required: true
  - type: textarea
    attributes:
      label: Problem
      description: Please add a clear and concise description of the problem you are seeking to solve with this feature request.
      placeholder: |
        Description
  - type: textarea
    attributes:
      label: Feature/ Solution
      description: Describe your feature/ solution and any alternative you've considered. If applicable, add screenshots/ videos or links about the feature here. References to games/ mods with this feature are very welcome.
      placeholder: |
        Description

        As an alternative I considered ...

        A similar feature can be found in ...

        Screenshots
    validations:
      required: true
