name: AUR Release

on:
  release:
    types: [published]

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# TODO "This action does not generate PKGBUILD for you, you must generate it yourself (e.g. by using actions before this action)."
#  https://github.com/search?o=desc&q=github-actions-deploy-aur+language%3AYAML&s=indexed&type=Code
#  labels: should have
#  assignees: IlanFrumer
jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.3.0
        with:
          pkgname: 0ad-boongui
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
