# Standard workflow for new commits

name: Code Quality

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  run-linters:
    # https://github.com/wearerequired/lint-action
    name: Code linter
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Whether the workflow run should also fail when linter failures are detected.
          continue_on_error: false
          # ESLint checks should fail even if there are no errors, just warnings.
          eslint_args: "--max-warnings 0"
          eslint: true
          # https://github.community/t/github-linting-remote-rejected
          # When auto_fix is enabled for the Lint workflow, no linter is allowed to modify the files in .github/workflows. To avoid a failed workflow, we limit the linter to js,ts files.
          eslint_extensions: js,ts
          auto_fix: true

  vale:
    # https://github.com/errata-ai/vale-action
    name: Text linter
    # Scope of file cases is set in .vale.ini
    if: ${{ always() }}
    needs: [run-linters]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          reporter: github-check
          fail_on_error: false
          # Filter results by added/modified file. i.e. reviewdog will report results as long as they are in added/modified file even if the results are not in actual diff.
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  todo_issues:
    # https://github.com/alstr/todo-to-issue-action
    name: Create TODO issues
    # jobs run in parallel by default, but i like them sequentially
    # jobs.<job_id>.needs - with "always()" not requiring successful prior job
    if: ${{ always() }}
    needs: [vale]
    runs-on: "ubuntu-latest"
    steps:
      - uses: "alstr/todo-to-issue-action@v4.6.6"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          # The SHA of the last pushed commit
          BEFORE: ${{ github.event.before }}
          # The SHA of the latest commit
          SHA: ${{ github.sha }}
          IGNORE: ".github/vale_styles"
          AUTO_ASSIGN: true
