name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          # ESLint checks should fail even if there are no errors and only warnings.
          eslint_args: "--max-warnings 0"
          # Normally Prettier is for formatting and Linters is for tracking down errors, but I use the .eslintrc.json file from 0ad and don't want to set up an extra format configuration for Prettier. Therefore it is off for now, might change it in the future.
          prettier: false
          # Whether the workflow run should also fail when linter failures are detected.
          continue_on_error: false
          # Whether linters should try to fix code style issues automatically. If some issues can be fixed, the action will commit and push the changes to the corresponding branch.
          auto_fix: true


