---
# This workflow handels the release of a new version.

name: Publish Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  repoVisualize:
    name: Repo visualization
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Update repo visualization for new release
        # https://github.com/githubocto/repo-visualizer
        # More details: https://githubnext.com/projects/repo-visualization
        uses: githubocto/repo-visualizer@main
        with:
          output_file: .github/Images/boonGUI_visualization.svg
          commit_message: "Update repo visualization image"
          excluded_paths: ".github,node_modules"
          excluded_globs: ".*"
          # BUG https://github.com/githubocto/repo-visualizer/issues/51
          file_colors: '{"dae":"#FD8D0E","png":"#55C7FF","props":"#929292","js":"#FECF0F","json":"#8162BE","ts":"#106BFF","txt":"#30D33B","xml":"#424242"}'

  buildRelease:
    name: Build Release
    needs: [repoVisualize]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Python enviroment
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.5

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitignore_parser

      - name: Create pyromod and zip files
        run: |
          python .github/build_scripts/make_pyromod.py

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.PYROMOD_MOD_NAME }} v${{ env.PYROMOD_MOD_VERSION }}
          tag_name: v${{ env.PYROMOD_MOD_VERSION }}
          files: |
            ${{ env.PYROMOD_PYROMOD_FILE_PATH }}
            ${{ env.PYROMOD_ZIP_FILE_PATH }}
          generate_release_notes: true

  # action does not generate PKGBUILD, results in failed workflow, Remove it for now!
  # aur-publish:
  #   # https://aur.archlinux.org/packages/0ad-boongui
  #   name: AUR Release
  #   needs: [repoVisualize, buildRelease]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v3

  #     - name: Publish AUR package
  #       uses: KSXGitHub/github-actions-deploy-aur@v2.5.0
  #       with:
  #         pkgname: 0ad-boongui
  #         pkgbuild: ./PKGBUILD
  #         commit_username: ${{ secrets.AUR_USERNAME }}
  #         commit_email: ${{ secrets.AUR_EMAIL }}
  #         ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
  #         commit_message: Update AUR package
  #         ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
